// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Crossfade curve types.
enum CrossfadeCurve {
  /// Equal power using sin/cos (recommended)
  /// Maintains constant perceived loudness
  equalPower,

  /// Linear fade (can sound "dipped" in the middle)
  linear,

  /// Square root curve (alternative equal power)
  squareRoot,

  /// S-curve for smoother transitions
  sCurve,
}
