// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// User-facing preference for the Android low-level audio API that Oboe wraps.
/// `Auto` lets Oboe choose (AAudio then OpenSL ES); the explicit variants force
/// that API first, with `Unspecified` as a safety net so audio still plays if the
/// chosen API is unavailable (e.g. AAudio on API 26). Bluetooth always defers to
/// Oboe's default since exclusive mode is wrong for the mixer path.
enum AudioApiPreference { auto, aAudio, openSles }
