// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Decode `path` once, computing waveform peaks (and later BS.1770 metrics).
/// Returns `None` for unsupported/unreachable files — callers treat that as a
/// silent skip.
///
/// `peak_buckets` controls the waveform resolution (typ. 240).
Future<AudioAnalysisResult?> analyzeAudioFile({
  required String path,
  required int peakBuckets,
}) => RustLib.instance.api.crateApiAudioAnalysisAnalyzeAudioFile(
  path: path,
  peakBuckets: peakBuckets,
);

class AudioAnalysisResult {
  final Float32List peaks;
  final double? lufs;
  final double? truePeakDb;
  final double? dr;
  final double? lra;
  final bool clipping;

  const AudioAnalysisResult({
    required this.peaks,
    this.lufs,
    this.truePeakDb,
    this.dr,
    this.lra,
    required this.clipping,
  });

  @override
  int get hashCode =>
      peaks.hashCode ^
      lufs.hashCode ^
      truePeakDb.hashCode ^
      dr.hashCode ^
      lra.hashCode ^
      clipping.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioAnalysisResult &&
          runtimeType == other.runtimeType &&
          peaks == other.peaks &&
          lufs == other.lufs &&
          truePeakDb == other.truePeakDb &&
          dr == other.dr &&
          lra == other.lra &&
          clipping == other.clipping;
}
