// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_tag_fields`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

Future<TagReadResult> readTags({required String path}) =>
    RustLib.instance.api.crateApiMetadataEditorReadTags(path: path);

Future<TagWriteResult> writeTags({
  required String path,
  required TagEditFields fields,
}) => RustLib.instance.api.crateApiMetadataEditorWriteTags(
  path: path,
  fields: fields,
);

Future<TagWriteResult> writeTagsToTemp({
  required String path,
  required TagEditFields fields,
  required String tempDir,
}) => RustLib.instance.api.crateApiMetadataEditorWriteTagsToTemp(
  path: path,
  fields: fields,
  tempDir: tempDir,
);

class TagEditFields {
  final String? title;
  final String? artist;
  final String? album;
  final String? albumArtist;
  final String? genre;
  final int? year;
  final int? trackNumber;
  final int? discNumber;

  const TagEditFields({
    this.title,
    this.artist,
    this.album,
    this.albumArtist,
    this.genre,
    this.year,
    this.trackNumber,
    this.discNumber,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      albumArtist.hashCode ^
      genre.hashCode ^
      year.hashCode ^
      trackNumber.hashCode ^
      discNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagEditFields &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          albumArtist == other.albumArtist &&
          genre == other.genre &&
          year == other.year &&
          trackNumber == other.trackNumber &&
          discNumber == other.discNumber;
}

class TagReadResult {
  final String? title;
  final String? artist;
  final String? album;
  final String? albumArtist;
  final String? genre;
  final int? year;
  final int? trackNumber;
  final int? discNumber;

  const TagReadResult({
    this.title,
    this.artist,
    this.album,
    this.albumArtist,
    this.genre,
    this.year,
    this.trackNumber,
    this.discNumber,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      albumArtist.hashCode ^
      genre.hashCode ^
      year.hashCode ^
      trackNumber.hashCode ^
      discNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagReadResult &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          albumArtist == other.albumArtist &&
          genre == other.genre &&
          year == other.year &&
          trackNumber == other.trackNumber &&
          discNumber == other.discNumber;
}

class TagWriteResult {
  final bool success;
  final String? error;
  final String? tempPath;

  const TagWriteResult({required this.success, this.error, this.tempPath});

  @override
  int get hashCode => success.hashCode ^ error.hashCode ^ tempPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagWriteResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          error == other.error &&
          tempPath == other.tempPath;
}
