// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_db`, `parse_peak`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Write ReplayGain tags to the file's primary (or first) tag.
/// `None` fields are left untouched so callers can update a subset.
Future<void> writeReplaygainTags({
  required String path,
  required ReplayGainTagFields fields,
}) => RustLib.instance.api.crateApiReplaygainWriteReplaygainTags(
  path: path,
  fields: fields,
);

/// Read ReplayGain tags from a file (None when missing or unreadable).
Future<ReplayGainTagFields?> readReplaygainTags({required String path}) =>
    RustLib.instance.api.crateApiReplaygainReadReplaygainTags(path: path);

class ReplayGainTagFields {
  /// Loudness gain for the track (dB).
  final double? trackGainDb;

  /// Track peak (linear).
  final double? trackPeak;

  /// Loudness gain for the whole album (dB).
  final double? albumGainDb;

  /// Album peak (linear).
  final double? albumPeak;

  const ReplayGainTagFields({
    this.trackGainDb,
    this.trackPeak,
    this.albumGainDb,
    this.albumPeak,
  });

  @override
  int get hashCode =>
      trackGainDb.hashCode ^
      trackPeak.hashCode ^
      albumGainDb.hashCode ^
      albumPeak.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReplayGainTagFields &&
          runtimeType == other.runtimeType &&
          trackGainDb == other.trackGainDb &&
          trackPeak == other.trackPeak &&
          albumGainDb == other.albumGainDb &&
          albumPeak == other.albumPeak;
}
