// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `addr`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Connect + open the share. Used by the ping flow; success means credentials
/// and transport are good. (smb2::connect applies a 5s timeout.)
Future<void> smbPing({
  required String host,
  required int port,
  required String share,
  required String user,
  required String pass,
}) => RustLib.instance.api.crateApiSmbApiSmbPing(
  host: host,
  port: port,
  share: share,
  user: user,
  pass: pass,
);

/// BFS walk of `root_path` (relative to the share) pushing one [SmbEntry] per
/// file or directory. `root_path` of "" lists the share root. One connection,
/// reused across directories.
Stream<SmbEntry> smbListShare({
  required String host,
  required int port,
  required String share,
  required String user,
  required String pass,
  required String rootPath,
}) => RustLib.instance.api.crateApiSmbApiSmbListShare(
  host: host,
  port: port,
  share: share,
  user: user,
  pass: pass,
  rootPath: rootPath,
);

/// Read a full (small) file into memory — cover art and tiny sidecars.
Future<Uint8List> smbReadFile({
  required String host,
  required int port,
  required String share,
  required String path,
  required String user,
  required String pass,
}) => RustLib.instance.api.crateApiSmbApiSmbReadFile(
  host: host,
  port: port,
  share: share,
  path: path,
  user: user,
  pass: pass,
);

/// Stream a file directly to `dest_path` on disk, reporting progress per chunk.
Stream<SmbProgress> smbDownloadFile({
  required String host,
  required int port,
  required String share,
  required String path,
  required String user,
  required String pass,
  required String destPath,
}) => RustLib.instance.api.crateApiSmbApiSmbDownloadFile(
  host: host,
  port: port,
  share: share,
  path: path,
  user: user,
  pass: pass,
  destPath: destPath,
);

class SmbEntry {
  final String name;
  final String path;
  final BigInt size;
  final bool isDir;

  const SmbEntry({
    required this.name,
    required this.path,
    required this.size,
    required this.isDir,
  });

  @override
  int get hashCode =>
      name.hashCode ^ path.hashCode ^ size.hashCode ^ isDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmbEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          size == other.size &&
          isDir == other.isDir;
}

class SmbProgress {
  final BigInt received;
  final BigInt total;
  final bool isComplete;

  const SmbProgress({
    required this.received,
    required this.total,
    required this.isComplete,
  });

  @override
  int get hashCode => received.hashCode ^ total.hashCode ^ isComplete.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmbProgress &&
          runtimeType == other.runtimeType &&
          received == other.received &&
          total == other.total &&
          isComplete == other.isComplete;
}
